# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - CORE_RELEASE=master
  matrix:
    - DB=MYSQL

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL
    - php: 5.6
      env: DB=MYSQL BEHAT_TEST=1
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - "if [ \"$BEHAT_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
  - "if [ \"$BEHAT_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension,silverstripe/cms; fi"
  - cd ~/builds/ss
  - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
  - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
  - "if [ \"$BEHAT_TEST\" = \"\" ]; then vendor/bin/phpunit siteconfig/tests; fi"
  - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat @siteconfig; fi"
